version: '3.7'

services:
  docker-python-example:
    container_name: docker-python-example
    hostname: docker-python-example
    image: docker/docker-python-example
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./logs:/logs
      - ./app/src:/app
    restart: always
    environment:
      DB_URL_CONNECT: "mysql+pymysql://root:root@mysql-db/bhut"
    depends_on:
      - mysql-db

  docker-nginx-example:
    container_name: docker-nginx-example
    hostname: docker-nginx-example
    image: docker/docker-nginx-example
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./logs:/logs
      - ./app/src:/app
    depends_on:
      - docker-python-example
    restart: always


  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bhut
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
